theme = "transparent"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
auto-save = true
true-color = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
S-b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
S-h = ":buffer-previous"
S-l = ":buffer-next"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
S-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"S-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]

